import React, {useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BadgeCheck, Check, ChevronLeft, Filter, Heart, MapPin, Menu, Search, ShieldCheck, Star, X} from 'lucide-react';
import './styles.css';

type Coach={id:string;name:string;role:string;location:string;distance:number;rating:number;reviews:number;price:number;tags:string[];initials:string;color:string;bio:string;availability:string};
const coaches:Coach[]=[
 {id:'sarah-mackenzie',name:'Sarah Mackenzie',role:'Personal trainer & women’s strength coach',location:'Inverness',distance:1.2,rating:4.9,reviews:48,price:42,tags:['Strength','Confidence','Beginners'],initials:'SM',color:'#dbe8e0',bio:'I help women feel stronger, more confident and at home in the gym — without intimidating plans or quick fixes.',availability:'Taking on new clients'},
 {id:'callum-fraser',name:'Callum Fraser',role:'Running coach & endurance specialist',location:'Elgin',distance:3.8,rating:4.8,reviews:31,price:35,tags:['Running','5K to marathon','Outdoor'],initials:'CF',color:'#dce9f4',bio:'Friendly, structured coaching for new runners and experienced racers across Moray.',availability:'2 spaces this month'},
 {id:'maya-patel',name:'Maya Patel',role:'Pilates & mobility coach',location:'Aberdeen',distance:6.4,rating:5,reviews:22,price:38,tags:['Pilates','Mobility','Back care'],initials:'MP',color:'#efe4d8',bio:'Move better, build lasting strength and enjoy training that meets you where you are.',availability:'Taking on new clients'},
 {id:'ewan-ross',name:'Ewan Ross',role:'Strength & conditioning coach',location:'Inverness',distance:8.1,rating:4.7,reviews:19,price:45,tags:['Strength','Sport','Rehab'],initials:'ER',color:'#e6e1ef',bio:'Practical strength coaching built around your goals, schedule and experience.',availability:'Limited availability'}
];
const go=(path:string)=>{location.hash=path};
function Logo(){return <button className="logo" onClick={()=>go('')} aria-label="Fitter home">fitter<i>.</i></button>}
function Header(){const[open,setOpen]=useState(false);return <header><div className="brand"><Logo/><small>Find your fit. Find your coach.</small></div><nav className={open?'open':''}><button onClick={()=>go('')}>Home</button><button onClick={()=>go('search')}>Find a Coach</button><button>Local Classes</button><button>Success Stories</button><button onClick={()=>{go('');setTimeout(()=>document.getElementById('trust')?.scrollIntoView(),50)}}>About</button><button className="navJoin">Become a Coach</button><button>Sign In</button></nav><button className="menu" onClick={()=>setOpen(!open)} aria-label="Toggle menu">{open?<X/>:<Menu/>}</button></header>}
function Avatar({coach,large=false}:{coach:Coach;large?:boolean}){return <div className={'avatar '+(large?'large':'')} style={{background:coach.color}}><span>{coach.initials}</span><div/></div>}
function Rating({c}:{c:Coach}){return <div className="rating"><Star size={17} fill="currentColor"/><b>{c.rating.toFixed(1)}</b><span>({c.reviews} Trusted Reviews)</span></div>}
function Card({c}:{c:Coach}){return <article className="coachCard" onClick={()=>go(`coach/${c.id}`)}><Avatar coach={c}/><div className="coachBody"><div className="cardTop"><div><span className="trusted"><ShieldCheck/> Trusted Coach</span><h3>{c.name}</h3></div><button className="heart" aria-label="Save coach" onClick={e=>e.stopPropagation()}><Heart/></button></div><p>{c.role}</p><Rating c={c}/><span className="place"><MapPin/>{c.location} · {c.distance} miles away</span><div className="tags">{c.tags.map(t=><span key={t}>{t}</span>)}</div><div className="cardFoot"><span><b>£{c.price}</b> / session</span><button>View profile</button></div></div></article>}
function SearchBox(){const[q,setQ]=useState('');return <div className="searchBox"><label><b>What do you want help with?</b><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&go(`search?q=${encodeURIComponent(q)}`)} placeholder="Strength, running, Pilates…"/></label><label><b>Where?</b><input defaultValue="Inverness"/></label><button onClick={()=>go(`search?q=${encodeURIComponent(q)}`)}><Search/> Find my coach</button></div>}
function Home(){const activities=[['Beginner Running Group','Tue, 7 May · 18:30','Inverness Park','6 spaces left'],['Outdoor Pilates','Sun, 12 May · 09:00','Bught Park','8 spaces left'],['HIIT Bootcamp','Thu, 9 May · 19:00','Inverness Fitness Hub','4 spaces left'],['Group Cycle Ride','Sat, 11 May · 08:30','Culloden Battlefield','10 spaces left']];return <><Header/><main><section className="hero heroPhoto"><div className="heroCopy"><span className="eyebrow">Welcome to Fitter</span><h1>Find your fit.<br/><em>Find your coach.</em></h1><p>Helping nice people find good, honest fitness professionals.</p><SearchBox/><div className="popular"><b>Popular:</b><span>Personal Trainer</span><span>Running Coach</span><span>Pilates</span><span>Strength Coach</span></div></div></section><section className="trustBar" id="trust"><div><Star/><span><b>Trusted Reviews</b>Every review is from genuine clients.</span></div><div><ShieldCheck/><span><b>Qualifications Verified</b>We verify qualifications and insurance.</span></div><div><Heart/><span><b>Trusted Coaches</b>Only the best make it onto Fitter.</span></div><aside><ShieldCheck/><span><b>How we keep it trustworthy</b>Every review and coach is checked.</span></aside></section><section className="featured homeSection"><div className="sectionHead"><h2>Trusted Coaches Near You</h2><button onClick={()=>go('search')}>View all coaches →</button></div><div className="grid four">{coaches.map(c=><Card c={c} key={c.id}/>)}</div></section><section className="activitySection"><div className="sectionHead"><h2>Classes Happening Nearby</h2><button>View all classes →</button></div><div className="activityGrid">{activities.map((a,i)=><article key={a[0]}><div className={'activityPhoto activity'+i}><span>{i===0?'RUN':i===1?'MOVE':i===2?'TRAIN':'RIDE'}</span></div><div><h3>{a[0]}</h3><p>◷ {a[1]}</p><p>⌖ {a[2]}</p><b>{a[3]}</b></div></article>)}</div></section><section className="stories"><div className="sectionHead"><h2>Real people. Real results.</h2><button>View more stories →</button></div><div className="storyGrid"><article><strong>“</strong><p>I never thought I’d enjoy running until I met my coach.</p><small>— Emma R. · Worked with Sarah</small></article><article><strong>“</strong><p>In 6 months I lost 12kg and built so much confidence.</p><small>— Daniel K. · Worked with James</small></article><article><strong>“</strong><p>Pilates has changed how I move and how I feel every day.</p><small>— Claire T. · Worked with Laura</small></article></div></section><section className="coachCta"><div><span className="ctaIcon"><BadgeCheck/></span><span><h2>Become a Trusted Coach</h2><p>Grow your coaching business with people actively looking for someone they can trust.</p><small>✓ 30-day free trial　 ✓ Build your profile　 ✓ Collect reviews　 ✓ Meet new clients</small></span></div><button>Start your free trial</button></section></main><Footer/></>}
function SearchPage(){const initial=new URLSearchParams(location.hash.split('?')[1]||'').get('q')||'';const[term,setTerm]=useState(initial);const found=useMemo(()=>coaches.filter(c=>!term||`${c.name} ${c.role} ${c.tags}`.toLowerCase().includes(term.toLowerCase())),[term]);return <><Header/><main className="page"><button className="back" onClick={()=>go('')}><ChevronLeft/> Home</button><span className="eyebrow">Find your person</span><h1 className="pageTitle">Coaches near Inverness</h1><p className="sub">{found.length} thoughtful matches, ranked by fit — never by who pays most.</p><div className="compact"><Search/><input value={term} onChange={e=>setTerm(e.target.value)} placeholder="Search speciality or coach"/><button><Filter/> Filters</button></div><div className="resultsLayout"><aside><h3>Refine your search</h3><label>Distance<select><option>Within 10 miles</option><option>Within 25 miles</option></select></label><label>Session price<select><option>Any price</option><option>Under £40</option></select></label><label className="check"><input type="checkbox" defaultChecked/> Trusted Coaches only</label><hr/><p><ShieldCheck/> We never sell higher rankings.</p></aside><section className="results"><div className="resultsMeta"><b>{found.length} coaches</b><select><option>Best match</option><option>Highest rated</option><option>Nearest</option></select></div>{found.map(c=><Card c={c} key={c.id}/>)}{!found.length&&<div className="empty"><h2>No exact matches yet</h2><p>Try a broader speciality or browse all local coaches.</p><button onClick={()=>setTerm('')}>Show all coaches</button></div>}</section></div></main><Footer/></>}
function Profile({id}:{id:string}){const c=coaches.find(x=>x.id===id)||coaches[0];return <><Header/><main className="page"><button className="back" onClick={()=>go('search')}><ChevronLeft/> Search results</button><section className="profileHero"><Avatar coach={c} large/><div><span className="trusted"><ShieldCheck/> Trusted Coach</span><h1 className="profileName">{c.name}</h1><p className="role">{c.role}</p><Rating c={c}/><span className="place"><MapPin/>{c.location} · {c.distance} miles away</span><div className="tags">{c.tags.map(t=><span key={t}>{t}</span>)}</div></div><aside className="booking"><small>Sessions from</small><div><b>£{c.price}</b> / hour</div><p>● {c.availability}</p><button onClick={()=>alert('Booking requests arrive in the next Fitter release.')}>Request a first chat</button><small>No payment required</small></aside></section><div className="profileGrid"><div><section className="panel"><span className="eyebrow">About</span><h2>Coaching that meets you where you are</h2><p>{c.bio}</p><p>My sessions are positive, practical and built around sustainable progress. We’ll start with a relaxed conversation about what you’d like to achieve.</p></section><section className="panel"><span className="eyebrow">Client experiences</span><h2>Trusted Reviews</h2><div className="review"><Rating c={c}/><p>“I felt listened to from the first session. The plan was realistic, encouraging and genuinely made me look forward to training.”</p><b>Emma L.</b><span><BadgeCheck/> Verified coaching client</span></div></section></div><aside className="panel credentials"><h3>Why {c.name.split(' ')[0]} is trusted</h3>{['Identity checked','Qualifications verified','Insurance verified'].map(v=><div key={v}><Check/>{v}</div>)}<hr/><p><ShieldCheck/> Fitter reviews evidence before showing this badge.</p></aside></div></main><Footer/></>}
function Footer(){return <footer><Logo/><p>Helping nice people find good, honest fitness professionals they can trust.</p><span>© 2026 Fitter · Privacy · Terms · Safety</span></footer>}
function App(){const hash=location.hash.slice(1);useState(()=>{addEventListener('hashchange',()=>location.reload())});if(hash.startsWith('coach/'))return <Profile id={hash.split('/')[1]}/>;if(hash.startsWith('search'))return <SearchPage/>;return <Home/>}
createRoot(document.getElementById('root')!).render(<App/>);
