import React, {useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BadgeCheck, Check, ChevronLeft, Filter, Heart, MapPin, Menu, Search, ShieldCheck, Star, X} from 'lucide-react';
import './styles.css';

type Coach={id:string;name:string;role:string;location:string;distance:number;rating:number;reviews:number;price:number;tags:string[];initials:string;color:string;bio:string;availability:string};
const coaches:Coach[]=[
 {id:'sarah-mackenzie',name:'Sarah Mackenzie',role:'Personal trainer & women’s strength coach',location:'Inverness',distance:1.2,rating:4.9,reviews:48,price:42,tags:['Strength','Confidence','Beginners'],initials:'SM',color:'#dbe8e0',bio:'I help women feel stronger, more confident and at home in the gym — without intimidating plans or quick fixes.',availability:'Taking on new clients'},
 {id:'callum-fraser',name:'Callum Fraser',role:'Running coach & endurance specialist',location:'Elgin',distance:3.8,rating:4.8,reviews:31,price:35,tags:['Running','5K to marathon','Outdoor'],initials:'CF',color:'#dce9f4',bio:'Friendly, structured coaching for new runners and experienced racers across Moray.',availability:'2 spaces this month'},
 {id:'maya-patel',name:'Maya Patel',role:'Pilates & mobility coach',location:'Aberdeen',distance:6.4,rating:5,reviews:22,price:38,tags:['Pilates','Mobility','Back care'],initials:'MP',color:'#efe4d8',bio:'Move better, build lasting strength and enjoy training that meets you where you are.',availability:'Taking on new clients'},
 {id:'ewan-ross',name:'Ewan Ross',role:'Strength & conditioning coach',location:'Inverness',distance:8.1,rating:4.7,reviews:19,price:45,tags:['Strength','Sport','Rehab'],initials:'ER',color:'#e6e1ef',bio:'Practical strength coaching built around your goals, schedule and experience.',availability:'Limited availability'}
];
const go=(path:string)=>{location.hash=path};
function Logo(){return <button className="logo" onClick={()=>go('')} aria-label="Fitter home">fitter<i>.</i></button>}
function Header(){const[open,setOpen]=useState(false);return <header><Logo/><nav className={open?'open':''}><button onClick={()=>go('search')}>Find a coach</button><button onClick={()=>{go('');setTimeout(()=>document.getElementById('trust')?.scrollIntoView(),50)}}>How trust works</button><button className="navJoin">Join as a coach</button></nav><button className="menu" onClick={()=>setOpen(!open)} aria-label="Toggle menu">{open?<X/>:<Menu/>}</button></header>}
function Avatar({coach,large=false}:{coach:Coach;large?:boolean}){return <div className={'avatar '+(large?'large':'')} style={{background:coach.color}}><span>{coach.initials}</span><div/></div>}
function Rating({c}:{c:Coach}){return <div className="rating"><Star size={17} fill="currentColor"/><b>{c.rating.toFixed(1)}</b><span>({c.reviews} Trusted Reviews)</span></div>}
function Card({c}:{c:Coach}){return <article className="coachCard" onClick={()=>go(`coach/${c.id}`)}><Avatar coach={c}/><div className="coachBody"><div className="cardTop"><div><span className="trusted"><ShieldCheck/> Trusted Coach</span><h3>{c.name}</h3></div><button className="heart" aria-label="Save coach" onClick={e=>e.stopPropagation()}><Heart/></button></div><p>{c.role}</p><Rating c={c}/><span className="place"><MapPin/>{c.location} · {c.distance} miles away</span><div className="tags">{c.tags.map(t=><span key={t}>{t}</span>)}</div><div className="cardFoot"><span><b>£{c.price}</b> / session</span><button>View profile</button></div></div></article>}
function SearchBox(){const[q,setQ]=useState('');return <div className="searchBox"><label><b>What do you want help with?</b><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&go(`search?q=${encodeURIComponent(q)}`)} placeholder="Strength, running, Pilates…"/></label><label><b>Where?</b><input defaultValue="Inverness"/></label><button onClick={()=>go(`search?q=${encodeURIComponent(q)}`)}><Search/> Find my coach</button></div>}
function Home(){return <><Header/><main><section className="hero"><div className="heroCopy"><span className="eyebrow">Trusted local fitness professionals</span><h1>Find your fit.<br/><em>Find your coach.</em></h1><p>Discover qualified coaches, read reviews from genuine clients, and choose with confidence.</p><SearchBox/><div className="miniTrust"><span><ShieldCheck/> Verified coaches</span><span><BadgeCheck/> Genuine reviews</span><span><Heart/> Built around you</span></div></div><div className="heroVisual"><div className="ring one"/><div className="ring two"/><div className="person"><div/><span/></div><div className="float ratingFloat"><b>4.9 ★</b><small>Trusted Reviews</small></div><div className="float verifyFloat"><ShieldCheck/><span><b>Trusted Coach</b><small>Fully verified</small></span></div></div></section><section className="intro"><div><span className="eyebrow">Coaching that feels right</span><h2>Good people. Real expertise.<br/>A better way to choose.</h2></div><p>Whether you’re starting from scratch or chasing a new goal, Fitter helps you find someone qualified, local and right for you.</p></section><section className="featured"><div className="sectionHead"><div><span className="eyebrow">Recommended near you</span><h2>Coaches you can trust</h2></div><button onClick={()=>go('search')}>See all coaches →</button></div><div className="grid">{coaches.slice(0,3).map(c=><Card c={c} key={c.id}/>)}</div></section><section className="trust" id="trust"><div><span className="eyebrow light">The Fitter standard</span><h2>Trust should be earned,<br/>not assumed.</h2><p>We check every Trusted Coach’s identity, qualifications and insurance. Trusted Reviews come from clients whose coaching relationship can be evidenced.</p><button onClick={()=>go('search')}>Find a Trusted Coach</button></div><div className="trustList">{[['01','Identity checked','We confirm that every coach is who they say they are.'],['02','Qualifications verified','Relevant certificates are reviewed before the badge appears.'],['03','Reviews with context','Clear verification helps you understand why a review is trusted.']].map(x=><div key={x[0]}><b>{x[0]}</b><span><strong>{x[1]}</strong>{x[2]}</span></div>)}</div></section><section className="cta"><span className="eyebrow">Your next chapter</span><h2>Ready to feel stronger?</h2><p>Find a coach who understands where you are — and where you want to go.</p><button onClick={()=>go('search')}>Explore coaches</button></section></main><Footer/></>}
function SearchPage(){const initial=new URLSearchParams(location.hash.split('?')[1]||'').get('q')||'';const[term,setTerm]=useState(initial);const found=useMemo(()=>coaches.filter(c=>!term||`${c.name} ${c.role} ${c.tags}`.toLowerCase().includes(term.toLowerCase())),[term]);return <><Header/><main className="page"><button className="back" onClick={()=>go('')}><ChevronLeft/> Home</button><span className="eyebrow">Find your person</span><h1 className="pageTitle">Coaches near Inverness</h1><p className="sub">{found.length} thoughtful matches, ranked by fit — never by who pays most.</p><div className="compact"><Search/><input value={term} onChange={e=>setTerm(e.target.value)} placeholder="Search speciality or coach"/><button><Filter/> Filters</button></div><div className="resultsLayout"><aside><h3>Refine your search</h3><label>Distance<select><option>Within 10 miles</option><option>Within 25 miles</option></select></label><label>Session price<select><option>Any price</option><option>Under £40</option></select></label><label className="check"><input type="checkbox" defaultChecked/> Trusted Coaches only</label><hr/><p><ShieldCheck/> We never sell higher rankings.</p></aside><section className="results"><div className="resultsMeta"><b>{found.length} coaches</b><select><option>Best match</option><option>Highest rated</option><option>Nearest</option></select></div>{found.map(c=><Card c={c} key={c.id}/>)}{!found.length&&<div className="empty"><h2>No exact matches yet</h2><p>Try a broader speciality or browse all local coaches.</p><button onClick={()=>setTerm('')}>Show all coaches</button></div>}</section></div></main><Footer/></>}
function Profile({id}:{id:string}){const c=coaches.find(x=>x.id===id)||coaches[0];return <><Header/><main className="page"><button className="back" onClick={()=>go('search')}><ChevronLeft/> Search results</button><section className="profileHero"><Avatar coach={c} large/><div><span className="trusted"><ShieldCheck/> Trusted Coach</span><h1 className="profileName">{c.name}</h1><p className="role">{c.role}</p><Rating c={c}/><span className="place"><MapPin/>{c.location} · {c.distance} miles away</span><div className="tags">{c.tags.map(t=><span key={t}>{t}</span>)}</div></div><aside className="booking"><small>Sessions from</small><div><b>£{c.price}</b> / hour</div><p>● {c.availability}</p><button onClick={()=>alert('Booking requests arrive in the next Fitter release.')}>Request a first chat</button><small>No payment required</small></aside></section><div className="profileGrid"><div><section className="panel"><span className="eyebrow">About</span><h2>Coaching that meets you where you are</h2><p>{c.bio}</p><p>My sessions are positive, practical and built around sustainable progress. We’ll start with a relaxed conversation about what you’d like to achieve.</p></section><section className="panel"><span className="eyebrow">Client experiences</span><h2>Trusted Reviews</h2><div className="review"><Rating c={c}/><p>“I felt listened to from the first session. The plan was realistic, encouraging and genuinely made me look forward to training.”</p><b>Emma L.</b><span><BadgeCheck/> Verified coaching client</span></div></section></div><aside className="panel credentials"><h3>Why {c.name.split(' ')[0]} is trusted</h3>{['Identity checked','Qualifications verified','Insurance verified'].map(v=><div key={v}><Check/>{v}</div>)}<hr/><p><ShieldCheck/> Fitter reviews evidence before showing this badge.</p></aside></div></main><Footer/></>}
function Footer(){return <footer><Logo/><p>Helping nice people find good, honest fitness professionals they can trust.</p><span>© 2026 Fitter · Privacy · Terms · Safety</span></footer>}
function App(){const hash=location.hash.slice(1);useState(()=>{addEventListener('hashchange',()=>location.reload())});if(hash.startsWith('coach/'))return <Profile id={hash.split('/')[1]}/>;if(hash.startsWith('search'))return <SearchPage/>;return <Home/>}
createRoot(document.getElementById('root')!).render(<App/>);
